files := src/CGPA_Calc.c inc/constants.h src/EnggLabCalculator.c src/main.c inc/main.h src/ScientificCalculator.c src/TrigonometricCalculator.c

all:
	gcc ${files} -o all.out -lm

clean:	
	rm -rf *.o *.out
	
run:all
	./all.out