files := CGPA_Calc.c constants.h EnggLabCalculator.c main.c main.h ScientificCalculator.c TrigonometricCalculator.c

all:
	gcc ${files} -o all.out -lm

clean:	
	rm -rf *.o *.out
	
run:all
	./all.out